### ISSUE TITLE
1. Распределение рабочих

### ISSUE THREAD

**Issue by ApatiSSS** [ApatiSSS/CommandQuest#3]
1. Создайте ветку workers.
2. В ней создайте папку workers, в которой уже распределите 15 рабочих на должность управляющих и рабочих
(p.s.) рабочих должно быть больше чем управляющих.

**Comment by RaZoRxzxc** [comment]
Сиваков
Кондратьев

**Comment by RaZoRxzxc** [comment]
Готово
