### ISSUE TITLE
2. Преподаватели и студенты (ЗАДАЧА ДЛЯ ДВОИХ)

### ISSUE THREAD

**Issue by ApatiSSS** [ApatiSSS/CommandQuest#5]
1PC
1.1 Создайте ветку Teachers и разбейте 20 преподавателей на условные предметы
1.2 Запушьте ветку и переключайтесь на ветку Students
1.3 Впишите номера преподавателей на каждого студента
1.4 После окончания работы вашего партнёра, сделайте Pull requests

2PC
2.1 Cоздайте ветку Students и разбейте 40 студентов на условные группы
2.2 Запушьте ветку и переключайтесь на ветку Teachers 
2.3 Впишите номера студентов на каждого преподавателя
2.4 После окончания работы вашего партнёра сделайте Pull request

**Comment by denovaa** [comment]
скворцов чупрун штапов петренко

**Comment by Yuhlop** [comment]
готово
